version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: sentiment_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

networks:
  mynetwork:
