"""Ajout des colonnes positive, negative et modification de content

Revision ID: 808b35dab239
Revises: 52932033e2e0
Create Date: 2025-02-12 11:00:18.582891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '808b35dab239'
down_revision = '52932033e2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweets')
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(length=280), nullable=False))
        batch_op.add_column(sa.Column('positive', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('negative', sa.Boolean(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', mysql.VARCHAR(length=280), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('negative')
        batch_op.drop_column('positive')
        batch_op.drop_column('text')

    op.create_table('tweets',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('text', mysql.TEXT(), nullable=False),
    sa.Column('positive', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('negative', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
